@extends('layouts.app')
@section('title','Katalog layanan | Izzan Digital Printing')
@section('page-title','Katalog layanan')
@section('content')
<div class="page-heading"><div><span class="section-kicker">LAYANAN PERCETAKAN</span><h1>Temukan layanan cetak Anda</h1><p>Pilihan layanan aktif dari Izzan Digital Printing.</p></div></div>
<form class="table-filters panel" method="get"><div class="search-field"><label class="sr-only" for="q">Cari layanan</label><input id="q" name="q" value="{{ request('q') }}" placeholder="Cari layanan…" maxlength="150"></div><button class="button primary">Cari</button><a class="text-link" href="{{ route('pelanggan.catalog') }}">Reset</a></form>
<div class="catalog-grid">@forelse($services as $service)<section class="panel catalog-card"><div class="catalog-cover">@if($service->image_path)<img src="{{ asset('storage/'.$service->image_path) }}" alt="{{ $service->name }}" loading="lazy" width="600" height="400">@else<div class="catalog-image-placeholder"><x-icon name="print"/><span>Gambar belum tersedia</span></div>@endif</div><span class="code-label">{{ $service->code }}</span><h2>{{ $service->name }}</h2><p>{{ $service->description ?: 'Hubungi toko untuk informasi spesifikasi layanan.' }}</p><div class="catalog-price">{{ $service->base_price !== null ? 'Rp '.number_format((float)$service->base_price,0,',','.') : 'Harga menyesuaikan spesifikasi' }}<span>Harga acuan · {{ $units[$service->unit] ?? $service->unit }}</span></div><a class="button primary catalog-order" href="{{ route('pelanggan.orders.create',['service'=>$service->id]) }}">Pesan layanan <x-icon name="arrow"/></a></section>@empty<section class="panel full-width"><div class="empty-state"><x-icon name="print"/><h3>Belum ada layanan yang ditampilkan</h3><p>Admin dapat menambahkan layanan aktif, atau Anda dapat mencoba kata pencarian lain.</p></div></section>@endforelse</div>
@include('partials.pagination',['page'=>$services])<div class="insight-note"><x-icon name="orders"/><p>Harga akhir diperiksa sesuai desain dan spesifikasi. Pilih layanan untuk mengirim pesanan dan desain kepada admin.</p></div>
@endsection
