@extends('layouts.app')
@section('content')
@php
$customer = $role === 'pelanggan';
$metrics = $customer ? [['orders','Pesanan saya','Riwayat pesanan Anda'],['wallet','Tagihan','Pembayaran pesanan'],['print','Layanan tersedia','Pilihan layanan cetak']] : [['orders','Total pesanan','Rekap seluruh pemesanan'],['print','Layanan aktif','Layanan yang tersedia'],['box','Bahan tercatat','Daftar bahan percetakan'],['wallet','Pembayaran diterima','Penerimaan, bukan laba']];
$serviceCount = \App\Models\Service::where('is_active',true)->count();
$materialCount = $customer ? null : \App\Models\Material::count();
$orderQuery = \App\Models\Order::query();
if($customer) $orderQuery->where('user_id',auth()->id());
$orderCount = (clone $orderQuery)->count();
$recentOrders = (clone $orderQuery)->latest('id')->limit(5)->get();
@endphp
<div class="page-heading"><div><span class="section-kicker">DASHBOARD {{ strtoupper($role) }}</span><h1>Selamat datang, {{ auth()->user()->name }} <span class="welcome-dot">✦</span></h1><p>{{ $customer ? 'Pantau kebutuhan cetak Anda dari satu tempat.' : 'Gambaran operasional percetakan dalam satu ruang kerja.' }}</p></div><span class="date-label">{{ now()->timezone('Asia/Jakarta')->format('d / m / Y') }}</span></div>
<section class="welcome-banner"><div><span class="banner-label"><span class="small-dot"></span>FONDASI APLIKASI SIAP</span><h2>{{ $customer ? 'Ruang untuk semua kebutuhan cetak Anda.' : 'Mulai dari data yang tertata.' }}</h2><p>{{ $customer ? 'Akun Anda sudah aktif. Jelajahi layanan di katalog; Anda dapat membuat pesanan dan mengikuti statusnya.' : 'Data layanan dan bahan sudah tersedia. Pesanan pelanggan dapat diperiksa dan dikelola melalui menu Pesanan.' }}</p>@if($role==='admin')<a class="button light" href="{{ route('admin.services.index') }}">Kelola layanan <x-icon name="arrow"/></a>@elseif($customer)<a class="button light" href="{{ route('pelanggan.catalog') }}">Jelajahi katalog <x-icon name="arrow"/></a>@else<a class="button light" href="#development-status">Lihat kesiapan fitur <x-icon name="arrow"/></a>@endif</div><div class="banner-art" aria-hidden="true"><x-icon name="print"/><span>IZZAN / WORKSPACE</span></div></section>
<div class="metrics-grid">@foreach($metrics as [$icon,$label,$description])<section class="metric-card"><div class="metric-header"><span>{{ $label }}</span><span class="metric-icon"><x-icon :name="$icon"/></span></div><strong class="metric-value">{{ $icon==='print' ? $serviceCount : ($icon==='box' ? $materialCount : ($icon==='orders' ? $orderCount : '—')) }}</strong><p>{{ $description }}</p><span class="metric-status">{{ in_array($icon,['print','box','orders']) ? 'Dari data aplikasi' : 'Menunggu modul data' }}</span></section>@endforeach</div>
<div class="content-grid"><section class="panel"><div class="panel-heading"><div><h2>{{ $customer ? 'Pesanan terbaru' : 'Aktivitas pemesanan' }}</h2><p>{{ $customer ? 'Riwayat pemesanan akan tampil di sini.' : 'Ringkasan transaksi dari pesanan yang tercatat.' }}</p></div><span class="neutral-chip">Terbaru</span></div>@if($recentOrders->isNotEmpty())<div class="table-scroll"><table><thead><tr><th>Pesanan terbaru</th><th>Status</th></tr></thead><tbody>@foreach($recentOrders as $recent)<tr><td>@if($role!=='manajer')<a class="edit-link" href="{{ route($role.'.orders.show',$recent) }}">{{ $recent->number }}</a>@else<strong>{{ $recent->number }}</strong>@endif<span class="table-description">{{ $recent->service_name }}</span></td><td><span class="order-status status-{{ $recent->status }}">{{ \App\Models\Order::STATUSES[$recent->status] }}</span></td></tr>@endforeach</tbody></table></div>@else<div class="empty-state"><span class="empty-icon"><x-icon name="orders"/></span><h3>Belum ada pesanan</h3><p>Pesanan akan tampil setelah pelanggan mengirim formulir pemesanan.</p></div>@endif<div class="panel-foot"><x-icon name="lock"/><span>Akses halaman dibatasi sesuai peran pengguna.</span></div></section>
<section class="panel readiness" id="development-status"><div class="panel-heading"><div><h2>Kesiapan fitur</h2><p>Tahap pengembangan aplikasi</p></div></div>
<div class="stage done"><span class="stage-icon"><x-icon name="check"/></span><div><h3>Akun & hak akses</h3><p>Login, logout, dan tiga peran</p></div><span class="ready-chip">Siap</span></div>
<div class="stage done"><span class="stage-icon"><x-icon name="check"/></span><div><h3>{{ $customer ? 'Katalog layanan' : 'Layanan & bahan' }}</h3><p>Data dasar percetakan</p></div><span class="ready-chip">Siap</span></div>
<div class="stage done"><span class="stage-icon"><x-icon name="check"/></span><div><h3>Pesanan & pemeriksaan</h3><p>Pesanan aktif · pembayaran menyusul</p></div><span class="ready-chip">Siap</span></div>
@if(!$customer)<div class="stage"><span class="stage-icon">04</span><div><h3>Analisis & laporan</h3><p>Rekap dan pengelompokan K-Means</p></div></div>@endif
<div class="readiness-note">{{ $customer ? 'Fitur ditambahkan secara bertahap agar alur pemesanan dapat diuji dengan baik.' : 'Analisis dimulai setelah unit, satuan volume, dan data pemesanan siap.' }}</div></section></div>
@if(!$customer)<section class="insight-note"><span class="metric-icon"><x-icon name="chart"/></span><div><strong>Memahami pola, mendukung keputusan.</strong><p>Rekap menampilkan transaksi. K-Means mengelompokkan pola yang mirip untuk membantu peninjauan kebutuhan bahan.</p></div></section>@endif
@endsection
