@extends('layouts.app')
@section('title','Chat '.$order->number.' | Izzan Digital Printing')
@section('page-title','Percakapan pesanan')
@section('content')
<div class="page-heading"><div><span class="section-kicker">CHAT PRIVAT PESANAN</span><h1>{{ $order->number }}</h1><p>{{ $order->service_name }} · {{ auth()->user()->role==='admin'?$order->user->name:'Tim admin Izzan Digital Printing' }}</p></div><div class="order-heading-actions"><a class="button secondary" href="{{ route(auth()->user()->role.'.chat.index') }}">Daftar chat</a><a class="button primary" href="{{ route(auth()->user()->role.'.orders.show',$order) }}">Detail & pembayaran</a></div></div>
@if($errors->any())<div class="error-summary" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="chat-workspace"><section class="panel chat-panel"><div class="chat-top"><span class="chat-avatar"><x-icon name="chat"/></span><div><strong>{{ auth()->user()->role==='admin'?'Percakapan dengan '.$order->user->name:'Percakapan dengan admin' }}</strong><p>Hanya admin toko dan pemilik pesanan yang dapat mengakses.</p></div></div>
<div class="chat-messages" id="chat-messages" role="log" aria-label="Riwayat percakapan" data-feed="{{ route(auth()->user()->role.'.chat.feed',$order) }}" data-latest="{{ $messages->first()?->id??0 }}" data-live="{{ $messages->currentPage()===1?'true':'false' }}">@include('chat.messages')</div>
<div class="chat-pagination">{{ $messages->links() }}</div><p class="chat-sync" id="chat-sync" role="status">{{ $messages->currentPage()===1?'Pesan baru diperiksa otomatis setiap 8 detik saat halaman terbuka.':'Menampilkan riwayat lama. Kembali ke halaman 1 untuk pesan terbaru.' }}</p>
<form class="chat-compose" method="post" action="{{ route(auth()->user()->role.'.chat.store',$order) }}">@csrf<input type="hidden" name="submission_key" value="{{ old('submission_key',(string)\Illuminate\Support\Str::uuid()) }}"><label for="chat-body">Pesan Anda</label><textarea id="chat-body" name="body" rows="3" maxlength="3000" required placeholder="Contoh: Apakah harga ini sudah termasuk desain dan ongkos kirim?">{{ old('body') }}</textarea><div><span>Maksimal 3.000 karakter · pesan teks</span><button class="button primary">Kirim pesan <x-icon name="arrow"/></button></div></form></section>
<aside class="panel order-details chat-guide"><span class="section-kicker">RINGKASAN KESEPAKATAN</span><h2>Diskusikan sebelum membayar</h2><span class="order-status status-{{ $order->status }}">{{ \App\Models\Order::STATUSES[$order->status] }}</span><dl><div><dt>Harga final saat ini</dt><dd class="final-price">{{ $order->final_total!==null?'Rp '.number_format((float)$order->final_total,2,',','.'):'Belum ditawarkan' }}</dd></div></dl><ol><li>Diskusikan ukuran, desain, harga, dan biaya kirim di chat.</li><li>Admin mencatat kesepakatan melalui penawaran harga di detail pesanan.</li><li>Pelanggan menyetujui penawaran, lalu mengajukan bukti pembayaran.</li></ol><p class="field-hint">Pesan chat tidak mengubah harga, status pesanan, atau pembayaran secara otomatis. Harga yang sudah disetujui dikunci oleh alur pesanan.</p><a class="button secondary" href="{{ route(auth()->user()->role.'.orders.show',$order) }}">Lihat penawaran resmi</a></aside></div>
<script src="{{ asset('js/chat.js') }}" defer></script>
@endsection
