@extends('layouts.app')
@section('title',($record->exists ? 'Edit ' : 'Tambah ').$meta['label'].' | Izzan Digital Printing')
@section('page-title',$meta['label'])
@section('content')
<div class="page-heading"><div><span class="section-kicker">DATA MASTER</span><h1>{{ $record->exists ? 'Edit' : 'Tambah' }} {{ strtolower($meta['label']) }}</h1><p>Lengkapi data dengan satuan yang digunakan toko.</p></div><a class="button secondary" href="{{ route('admin.'.$meta['key'].'.index') }}">Kembali ke daftar</a></div>
<section class="panel form-panel"><form method="post" enctype="multipart/form-data" action="{{ $record->exists ? route('admin.'.$meta['key'].'.update',$record->id) : route('admin.'.$meta['key'].'.store') }}">@csrf @if($record->exists) @method('PUT') @endif
<div class="form-grid">
@if($meta['key']==='services')
<div class="full-width image-upload-panel"><div><label for="image">Gambar layanan</label><p class="field-hint">JPG, PNG, atau WebP · maksimal 2 MB dan 6000 × 6000 piksel. Gambar tampil di katalog pelanggan.</p><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp" aria-describedby="image-hint"><p class="field-hint" id="image-hint">Kosongkan untuk mempertahankan gambar lama. Jika validasi gagal, pilih ulang file gambar.</p>@error('image')<p class="error" role="alert">{{ $message }}</p>@enderror<p class="field-hint" id="image-preview-status" aria-live="polite"></p></div>
<div class="image-preview"><img id="image-preview" src="{{ $record->image_path ? asset('storage/'.$record->image_path) : '' }}" alt="Pratinjau gambar layanan" @if(!$record->image_path) hidden @endif><span id="image-placeholder" @if($record->image_path) hidden @endif><x-icon name="print"/><small>Pratinjau gambar</small></span></div></div>
@endif
<div><label for="code">Kode <span class="required">*</span></label><input id="code" name="code" value="{{ old('code',$record->code) }}" maxlength="30" placeholder="{{ $meta['key']==='services' ? 'LYN-001' : 'BHN-001' }}" required><p class="field-hint">Gunakan huruf, angka, tanda - atau _.</p>@error('code')<p class="error" role="alert">{{ $message }}</p>@enderror</div>
<div><label for="name">Nama {{ strtolower($meta['label']) }} <span class="required">*</span></label><input id="name" name="name" value="{{ old('name',$record->name) }}" maxlength="150" required>@error('name')<p class="error" role="alert">{{ $message }}</p>@enderror</div>
<div><label for="unit">Satuan <span class="required">*</span></label><select id="unit" name="unit" required><option value="">Pilih satuan</option>@foreach($units as $value=>$label)<option value="{{ $value }}" @selected(old('unit',$record->unit)===$value)>{{ $label }}</option>@endforeach</select>@error('unit')<p class="error" role="alert">{{ $message }}</p>@enderror</div>
@if($meta['key']==='services')<div><label for="minimum_quantity">Minimal jumlah pesanan *</label><input id="minimum_quantity" name="minimum_quantity" type="number" min="1" max="1000000" step="1" value="{{ old('minimum_quantity',$record->minimum_quantity ?? 1) }}" required><p class="field-hint">Jumlah barang/lembar. Nilai 1 mengizinkan pesanan satu barang.</p>@error('minimum_quantity')<p class="error">{{ $message }}</p>@enderror</div><div><label for="base_price">Harga acuan per satuan (Rp)</label><input id="base_price" name="base_price" type="text" inputmode="decimal" maxlength="30" data-rupiah value="{{ old('base_price',$record->base_price) }}" placeholder="Opsional"><p class="field-hint">Kosongkan jika harga perlu diperiksa berdasarkan desain.</p>@error('base_price')<p class="error" role="alert">{{ $message }}</p>@enderror</div>@endif
<div><label for="is_active">Status <span class="required">*</span></label><select id="is_active" name="is_active"><option value="1" @selected((string)old('is_active',$record->exists ? (int)$record->is_active : 1)==='1')>Aktif</option><option value="0" @selected((string)old('is_active',$record->exists ? (int)$record->is_active : 1)==='0')>Nonaktif</option></select><p class="field-hint">Nonaktifkan data yang tidak dipakai; riwayat tetap tersimpan.</p>@error('is_active')<p class="error" role="alert">{{ $message }}</p>@enderror</div>
<div class="full-width"><label for="description">Keterangan</label><textarea id="description" name="description" rows="4" maxlength="2000" placeholder="Spesifikasi atau catatan tambahan">{{ old('description',$record->description) }}</textarea>@error('description')<p class="error" role="alert">{{ $message }}</p>@enderror</div>
</div><div class="form-actions"><a class="button secondary" href="{{ route('admin.'.$meta['key'].'.index') }}">Batal</a><button class="button primary" type="submit">Simpan {{ strtolower($meta['label']) }} <x-icon name="check"/></button></div></form></section>
@endsection
