@extends('layouts.app')
@section('title',$meta['label'].' | Izzan Digital Printing')
@section('page-title',$meta['label'])
@section('content')
<div class="page-heading"><div><span class="section-kicker">DATA MASTER</span><h1>Data {{ strtolower($meta['label']) }}</h1><p>{{ $meta['key']==='services' ? 'Atur layanan, satuan volume, dan harga acuan percetakan.' : 'Catat bahan dan satuannya sebelum menyusun alur pemakaian.' }}</p></div><a class="button primary" href="{{ route('admin.'.$meta['key'].'.create') }}">+ Tambah {{ strtolower($meta['label']) }}</a></div>
<section class="panel"><form class="table-filters" method="get"><div class="search-field"><label class="sr-only" for="q">Cari nama atau kode</label><input id="q" name="q" value="{{ request('q') }}" placeholder="Cari nama atau kode…" maxlength="150"></div><div><label class="sr-only" for="status">Status</label><select id="status" name="status"><option value="">Semua status</option><option value="active" @selected(request('status')==='active')>Aktif</option><option value="inactive" @selected(request('status')==='inactive')>Nonaktif</option></select></div><button class="button primary" type="submit">Terapkan</button><a class="text-link" href="{{ route('admin.'.$meta['key'].'.index') }}">Reset</a></form>
<div class="table-scroll"><table><thead><tr>@if($meta['key']==='services')<th>Gambar</th>@endif<th>Kode</th><th>Nama {{ strtolower($meta['label']) }}</th><th>Satuan</th>@if($meta['key']==='services')<th>Harga acuan</th>@endif<th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($records as $record)<tr>@if($meta['key']==='services')<td>@if($record->image_path)<img class="service-thumbnail" src="{{ asset('storage/'.$record->image_path) }}" alt="{{ $record->name }}" loading="lazy">@else<span class="thumbnail-placeholder"><x-icon name="print"/></span>@endif</td>@endif<td><span class="code-label">{{ $record->code }}</span></td><td><strong>{{ $record->name }}</strong><span class="table-description">{{ \Illuminate\Support\Str::limit($record->description,70) }}</span></td><td>{{ $units[$record->unit] ?? $record->unit }}</td>@if($meta['key']==='services')<td>{{ $record->base_price !== null ? 'Rp '.number_format((float)$record->base_price,0,',','.') : 'Belum ditentukan' }}</td>@endif<td><span class="{{ $record->is_active ? 'ready-chip' : 'neutral-chip' }}">{{ $record->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><a class="edit-link" href="{{ route('admin.'.$meta['key'].'.edit',$record->id) }}">Edit <span class="sr-only">{{ $record->name }}</span></a></td></tr>
@empty<tr><td colspan="{{ $meta['key']==='services' ? 7 : 5 }}"><div class="empty-state"><span class="empty-icon"><x-icon :name="$meta['icon']"/></span><h3>{{ request()->filled('q') || request()->filled('status') ? 'Tidak ada data yang cocok' : 'Belum ada data '.strtolower($meta['label']) }}</h3><p>Tambahkan data baru atau sesuaikan filter pencarian.</p></div></td></tr>@endforelse
</tbody></table></div>@include('partials.pagination',['page'=>$records])</section>
<div class="insight-note"><x-icon name="box"/><p>{{ $meta['key']==='services' ? 'Harga acuan belum menjadi harga akhir pesanan. Satuan berbeda akan diperlakukan terpisah dalam analisis.' : 'Daftar bahan ini belum menghitung stok atau pemakaian. Perhitungan stok memerlukan pencatatan pergerakan bahan.' }}</p></div>
@endsection
