@extends('layouts.app')
@section('title','Buat pesanan | Izzan Digital Printing')
@section('page-title','Pesanan baru')
@section('content')
<div class="page-heading"><div><span class="section-kicker">CETAK SESUAI KEBUTUHAN ANDA</span><h1>Buat pesanan</h1><p>Satu layanan dan satu desain per pesanan. Jumlah dan ukuran dapat bervariasi.</p></div><a class="button secondary" href="{{ route('pelanggan.orders.index') }}">Pesanan saya</a></div>
@if($services->isEmpty())<section class="panel empty-state"><h3>Belum ada layanan aktif</h3><p>Admin perlu menambahkan layanan sebelum Anda dapat memesan.</p></section>@else
<div class="order-form-layout"><section class="panel form-panel"><form method="post" enctype="multipart/form-data" action="{{ route('pelanggan.orders.store') }}" id="order-form">@csrf
@if($errors->any())<div class="error-summary" role="alert"><strong>Periksa isian berikut:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<h2 class="form-section-title">01 · Pilih layanan & spesifikasi</h2><div class="form-grid"><div class="full-width"><label for="service_id">Layanan *</label><select id="service_id" name="service_id" required><option value="">Pilih layanan cetak</option>@foreach($services as $service)<option value="{{ $service->id }}" data-unit="{{ $service->unit }}" data-price="{{ $service->base_price }}" data-min="{{ $service->minimum_quantity }}" @selected((int)old('service_id',$selected)===$service->id)>{{ $service->name }} · {{ $service->unit==='m2'?'m²':$service->unit }}</option>@endforeach</select></div>
<div><label for="quantity">Jumlah *</label><input id="quantity" name="quantity" type="number" min="1" max="1000000" step="1" value="{{ old('quantity',1) }}" required><p class="field-hint" id="quantity-hint">Masukkan jumlah barang atau lembar.</p></div>
<div id="width-field"><label for="width">Panjang per barang (meter)</label><input id="width" name="width" type="number" min="0.001" max="1000" step="0.001" value="{{ old('width') }}" placeholder="Contoh: 2.5"></div>
<div id="height-field"><label for="height">Lebar per barang (meter)</label><input id="height" name="height" type="number" min="0.001" max="1000" step="0.001" value="{{ old('height') }}" placeholder="Contoh: 1.2"></div></div>
<h2 class="form-section-title">02 · Desain & catatan</h2><label for="design_mode">Pilihan desain *</label><select id="design_mode" name="design_mode"><option value="upload" @selected(old('design_mode','upload')==='upload')>Saya memiliki desain sendiri</option><option value="assistance" @selected(old('design_mode')==='assistance')>Minta bantuan desain dari toko</option></select><label for="design">File desain</label><input id="design" name="design" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"><p class="field-hint">JPG, PNG, WebP atau PDF maksimal 2 MB. Wajib jika memakai desain sendiri. Pilih ulang file jika validasi gagal.</p><label for="customer_notes">Catatan spesifikasi / arahan desain</label><textarea id="customer_notes" name="customer_notes" rows="4" maxlength="3000" placeholder="Contoh: warna, finishing, atau arahan desain yang dibutuhkan">{{ old('customer_notes') }}</textarea><p class="field-hint">Wajib diisi jika meminta bantuan desain. Biaya desain diperiksa oleh admin.</p>
<h2 class="form-section-title">03 · Penyerahan pesanan</h2><label for="delivery_method">Metode penyerahan *</label><select id="delivery_method" name="delivery_method"><option value="pickup" @selected(old('delivery_method','pickup')==='pickup')>Ambil di toko</option><option value="shipping" @selected(old('delivery_method')==='shipping')>Kirim ke alamat</option></select><div id="address-field"><label for="delivery_address">Alamat pengiriman *</label><textarea id="delivery_address" name="delivery_address" maxlength="1000" rows="3" placeholder="Nama penerima, alamat lengkap, kota, dan kode pos">{{ old('delivery_address') }}</textarea></div><div class="form-actions"><button class="button primary">Kirim untuk diperiksa <x-icon name="arrow"/></button></div></form></section>
<aside class="panel estimate-panel"><span class="section-kicker">RINGKASAN AWAL</span><h2>Estimasi pesanan</h2><div class="estimate-row"><span>Total volume</span><strong id="estimate-volume">Pilih layanan</strong></div><div class="estimate-row"><span>Estimasi harga acuan</span><strong id="estimate-price">—</strong></div><p>Harga final ditentukan admin setelah desain dan spesifikasi diperiksa. Biaya desain serta pengiriman belum termasuk dalam estimasi.</p><div class="readiness-note">Contoh: 3 spanduk × 2,5 m × 1,2 m = 9 m². Brosur 250 lembar tetap dihitung sebagai 250 lembar.</div></aside></div>
<script src="{{ asset('js/orders.js') }}" defer></script>
@endif
@endsection
