@extends('layouts.app')
@section('title','Pesanan | Izzan Digital Printing')
@section('page-title','Pesanan')
@section('content')
@php $prefix=auth()->user()->role==='admin'?'admin':'pelanggan'; @endphp
<div class="page-heading"><div><span class="section-kicker">PEMESANAN</span><h1>{{ $prefix==='admin' ? 'Kelola pesanan' : 'Pesanan saya' }}</h1><p>{{ $prefix==='admin' ? 'Periksa desain, tentukan harga final, dan pantau pengerjaan.' : 'Pantau pemeriksaan, penawaran harga, dan perjalanan pesanan Anda.' }}</p></div>@if($prefix==='pelanggan')<a class="button primary" href="{{ route('pelanggan.orders.create') }}">+ Buat pesanan</a>@endif</div>
<section class="panel"><form class="table-filters" method="get"><div class="search-field"><label class="sr-only" for="q">Cari nomor atau layanan</label><input id="q" name="q" placeholder="Cari nomor pesanan atau layanan…" value="{{ request('q') }}" maxlength="150"></div><div><label class="sr-only" for="status">Status</label><select id="status" name="status"><option value="">Semua status</option>@foreach($statuses as $key=>$label)<option value="{{ $key }}" @selected(request('status')===$key)>{{ $label }}</option>@endforeach</select></div><button class="button primary">Terapkan</button></form>
<div class="table-scroll"><table><thead><tr><th>Pesanan</th>@if($prefix==='admin')<th>Pelanggan</th>@endif<th>Jumlah & volume</th><th>Status</th><th>Harga final</th><th></th></tr></thead><tbody>@forelse($orders as $order)<tr><td><strong>{{ $order->number }}</strong><span class="table-description">{{ $order->service_name }} · {{ $order->created_at->timezone('Asia/Jakarta')->format('d M Y') }}</span></td>@if($prefix==='admin')<td>{{ $order->user->name }}</td>@endif<td>{{ number_format($order->quantity,0,',','.') }} {{ in_array($order->unit,['m','m2'])?'buah':$order->unit }}<span class="table-description">{{ rtrim(rtrim($order->volume,'0'),'.') }} {{ $order->unit==='m2'?'m²':$order->unit }}</span></td><td><span class="order-status status-{{ $order->status }}">{{ $statuses[$order->status] }}</span></td><td>{{ $order->final_total!==null?'Rp '.number_format((float)$order->final_total,2,',','.'):'Belum ditentukan' }}</td><td><a class="edit-link" href="{{ route($prefix.'.orders.show',$order) }}">Detail</a></td></tr>@empty<tr><td colspan="6"><div class="empty-state"><x-icon name="orders"/><h3>Belum ada pesanan yang ditampilkan</h3><p>Buat pesanan baru atau sesuaikan filter pencarian.</p></div></td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['page'=>$orders])</section>
@endsection
