<!DOCTYPE html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Nota {{ $order->number }}</title><link rel="stylesheet" href="{{ asset('css/receipt.css') }}"><script src="{{ asset('js/receipt.js') }}" defer></script></head><body>
<div class="print-toolbar"><a href="{{ route((auth()->user()->role==='admin'?'admin':'pelanggan').'.orders.show',$order) }}">← Kembali ke pesanan</a><button type="button" id="print-receipt">Cetak / Simpan PDF</button><p>Pilih printer atau “Save as PDF” pada dialog cetak browser.</p></div>
<main class="receipt"><header><div><span class="kicker">IZZAN</span><h1>Digital Printing</h1>@if(config('printing.address'))<p>{{ config('printing.address') }}</p>@endif @if(config('printing.phone'))<p>{{ config('printing.phone') }}</p>@endif</div><div class="receipt-title"><h2>NOTA PESANAN</h2><strong>{{ $order->number }}</strong><p>{{ $order->created_at->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB</p><span class="payment-badge">{{ $totals['label'] }}</span></div></header>
<p class="receipt-demo">SIMULASI PENGEMBANGAN · Metode pembayaran masih dummy. Bukan bukti transaksi nyata.</p><section class="receipt-parties"><div><h3>Pelanggan</h3><strong>{{ $order->user->name }}</strong><p>{{ $order->user->email }}<br>{{ $order->user->phone ?: 'Nomor telepon belum tersedia' }}</p></div><div><h3>Penyerahan & pengerjaan</h3><p>{{ $order->delivery_method==='pickup'?'Ambil di toko':'Kirim ke alamat' }}<br>{{ \App\Models\Order::STATUSES[$order->status] }}</p>@if($order->delivery_address)<p class="multiline">{{ $order->delivery_address }}</p>@endif</div></section>
<table class="spec-table"><thead><tr><th>Layanan / spesifikasi</th><th>Jumlah</th><th>Volume</th></tr></thead><tbody><tr><td><strong>{{ $order->service_name }}</strong>@if($order->width)<p>{{ (float)$order->width }} {{ $order->height?'× '.(float)$order->height:'' }} meter per barang</p>@endif<p>{{ $order->design_mode==='upload'?'Desain pelanggan':'Bantuan desain toko' }}</p></td><td>{{ number_format($order->quantity,0,',','.') }} {{ in_array($order->unit,['m','m2'])?'buah':$order->unit }}</td><td>{{ rtrim(rtrim($order->volume,'0'),'.') }} {{ $order->unit==='m2'?'m²':$order->unit }}</td></tr></tbody></table>
<div class="receipt-totals"><div><span>Estimasi awal</span><strong>{{ $order->estimated_total!==null?'Rp '.number_format((float)$order->estimated_total,2,',','.'):'Belum ditentukan' }}</strong></div><div class="final-row"><span>Nilai pesanan / harga final</span><strong>{{ $order->final_total!==null?'Rp '.number_format((float)$order->final_total,2,',','.'):'Belum ditentukan' }}</strong></div><div><span>Pembayaran diverifikasi</span><strong>Rp {{ number_format((float)$totals['verified'],2,',','.') }}</strong></div><div><span>Menunggu verifikasi (belum diterima)</span><strong>Rp {{ number_format((float)$totals['pending'],2,',','.') }}</strong></div><div class="balance-row"><span>Sisa tagihan</span><strong>{{ $totals['remaining']!==null?'Rp '.number_format((float)$totals['remaining'],2,',','.'):'Menunggu harga final' }}</strong></div></div>
@if($order->payments->isNotEmpty())<section><h3>Riwayat pembayaran</h3><div class="receipt-table-wrap"><table><thead><tr><th>Bukti</th><th>Tanggal / metode</th><th>Nominal</th><th>Status</th></tr></thead><tbody>@foreach($order->payments as $payment)<tr><td>#{{ $payment->id }}</td><td>{{ $payment->paid_on->format('d M Y') }}<p>{{ $payment->method_label }}</p></td><td>Rp {{ number_format((float)$payment->amount,2,',','.') }}</td><td>{{ \App\Models\Payment::STATUSES[$payment->status] }}</td></tr>@endforeach</tbody></table></div></section>@endif
<section class="receipt-notes"><h3>Catatan pesanan</h3><p class="multiline">{{ $order->customer_notes ?: 'Tidak ada catatan pelanggan.' }}</p>@if($order->admin_notes)<h3>Hasil pemeriksaan admin</h3><p class="multiline">{{ $order->admin_notes }}</p>@endif</section>
<footer><strong>Terima kasih telah memilih Izzan Digital Printing.</strong><p>Pesanan hanya diserahkan setelah lunas. Status pengerjaan tidak menunjukkan status pembayaran.</p><p>Nota menampilkan data saat dicetak: {{ now()->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB. Nilai pembayaran diterima hanya mencakup bukti yang diverifikasi admin.</p></footer></main></body></html>
