@extends('layouts.app')
@section('title',$order->number.' | Izzan Digital Printing')
@section('page-title','Detail pesanan')
@section('content')
@php $admin=auth()->user()->role==='admin'; $prefix=$admin?'admin':'pelanggan'; @endphp
<div class="page-heading"><div><span class="section-kicker">DETAIL PESANAN</span><h1>{{ $order->number }}</h1><p>{{ $order->service_name }} · Dibuat {{ $order->created_at->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB</p></div><a class="button secondary" href="{{ route($prefix.'.orders.index') }}">Kembali ke pesanan</a></div>
@if($errors->any())<div class="error-summary" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="order-detail-grid"><section class="panel order-details"><span class="order-status status-{{ $order->status }}">{{ $statuses[$order->status] }}</span><h2>Spesifikasi pesanan</h2><dl><div><dt>Layanan</dt><dd>{{ $order->service_name }}</dd></div><div><dt>Jumlah</dt><dd>{{ number_format($order->quantity,0,',','.') }} {{ in_array($order->unit,['m','m2'])?'buah':$order->unit }}</dd></div>@if($order->width)<div><dt>Ukuran per barang</dt><dd>{{ (float)$order->width }} {{ $order->height?'× '.(float)$order->height:'' }} meter</dd></div>@endif<div><dt>Total volume</dt><dd>{{ rtrim(rtrim($order->volume,'0'),'.') }} {{ $order->unit==='m2'?'m²':$order->unit }}</dd></div><div><dt>Desain</dt><dd>{{ $order->design_mode==='upload'?'Desain pelanggan':'Bantuan desain toko' }}</dd></div><div><dt>Penyerahan</dt><dd>{{ $order->delivery_method==='pickup'?'Ambil di toko':'Kirim ke alamat' }}</dd></div>@if($order->delivery_address)<div><dt>Alamat pengiriman</dt><dd class="multiline">{{ $order->delivery_address }}</dd></div>@endif</dl><h3>Catatan pelanggan</h3><p class="multiline">{{ $order->customer_notes ?: 'Tidak ada catatan.' }}</p>@if($order->design_path)<a class="button secondary" href="{{ route($prefix.'.orders.design',$order) }}">Unduh file desain</a>@endif
@if($admin)<h3>Kontak pelanggan</h3><p>{{ $order->user->name }}<br>{{ $order->user->email }}<br>{{ $order->user->phone ?: 'Nomor telepon belum tersedia' }}</p>@endif
</section><div><section class="panel order-details"><h2>Harga & pemeriksaan</h2><dl><div><dt>Estimasi awal</dt><dd>{{ $order->estimated_total!==null?'Rp '.number_format((float)$order->estimated_total,2,',','.'):'Perlu pemeriksaan' }}</dd></div><div><dt>Harga final total</dt><dd class="final-price">{{ $order->final_total!==null?'Rp '.number_format((float)$order->final_total,2,',','.'):'Belum ditentukan' }}</dd></div></dl><p class="field-hint">Harga final adalah nilai pesanan, bukan bukti pembayaran. Modul pembayaran belum tersedia.</p>@if($order->admin_notes)<h3>Catatan admin</h3><p class="multiline">{{ $order->admin_notes }}</p>@endif
@if(!$admin && $order->status==='quoted')<form method="post" action="{{ route('pelanggan.orders.approve',$order) }}">@csrf<input type="hidden" name="accepted_total" value="{{ $order->final_total }}"><button class="button primary action-button">Setujui harga {{ 'Rp '.number_format((float)$order->final_total,2,',','.') }}</button></form><p class="field-hint">Persetujuan harga memungkinkan admin memulai pengerjaan.</p>@endif
@if(!$admin && in_array($order->status,['pending','revision','quoted']))<form method="post" action="{{ route('pelanggan.orders.cancel',$order) }}" data-confirm="Batalkan pesanan ini? Pesanan yang dibatalkan tetap tersimpan dalam riwayat.">@csrf<button class="button secondary action-button">Batalkan pesanan</button></form>@endif
@if($admin && in_array($order->status,['pending','revision','quoted']))<form method="post" action="{{ route('admin.orders.review',$order) }}">@csrf<label for="action">Hasil pemeriksaan</label><select id="action" name="action"><option value="quote" @selected(old('action')==='quote')>Tawarkan harga final</option><option value="revision" @selected(old('action')==='revision')>Minta perbaikan / klarifikasi</option></select><label for="final_total">Harga final total (Rp)</label><input id="final_total" name="final_total" type="number" min="0.01" max="999999999999.99" step="0.01" value="{{ old('final_total',$order->final_total) }}"><p class="field-hint">Total termasuk biaya desain atau kirim jika ada. Jelaskan rinciannya pada catatan.</p><label for="admin_notes">Catatan pemeriksaan</label><textarea id="admin_notes" name="admin_notes" rows="3" maxlength="3000">{{ old('admin_notes',$order->admin_notes) }}</textarea><p class="field-hint">Wajib jika meminta perbaikan.</p><button class="button primary action-button">Simpan pemeriksaan</button></form>@endif
@if($admin && in_array($order->status,['confirmed','processing','completed']))@php $next=match($order->status){'confirmed'=>'processing','processing'=>'completed',default=>$order->delivery_method==='shipping'?'shipped':'collected'}; @endphp<form method="post" action="{{ route('admin.orders.progress',$order) }}">@csrf<input type="hidden" name="status" value="{{ $next }}"><label for="note">Catatan pengerjaan / pengiriman</label><textarea id="note" name="note" rows="3" maxlength="3000" placeholder="Catatan atau nomor resi jika tersedia">{{ old('note') }}</textarea><button class="button primary action-button">Tandai: {{ $statuses[$next] }}</button></form>@endif
</section>
@if(!$admin && $order->status==='revision')<section class="panel order-details"><h2>Kirim perbaikan</h2><form method="post" enctype="multipart/form-data" action="{{ route('pelanggan.orders.revise',$order) }}">@csrf<label for="design">File desain pengganti (opsional)</label><input id="design" name="design" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"><p class="field-hint">Maksimal 2 MB. Kosongkan untuk mempertahankan file sebelumnya.</p><label for="customer_notes">Catatan perbaikan *</label><textarea id="customer_notes" name="customer_notes" maxlength="3000" rows="3" required>{{ old('customer_notes',$order->customer_notes) }}</textarea><button class="button primary action-button">Kirim perbaikan</button></form></section>@endif
</div></div>
<section class="panel order-timeline"><h2>Riwayat pesanan</h2>@foreach($order->events as $event)<div class="timeline-event"><span class="timeline-dot"></span><div><strong>{{ $statuses[$event->status] }}</strong><p class="multiline">{{ $event->note }}</p><small>{{ $event->created_at->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB · {{ $event->user->role==='admin'?'Admin':'Pelanggan' }}</small></div></div>@endforeach</section>
@endsection
